Points:
  Points-On-Kill: 10
  Points-On-Death: 5
  Points-On-Respawn: 200
Options:
  Auto-Close-Upgrade-Menu: true
  Food-Heal: 1
upgrades:
  health:
    price: 0
    multiplier: 1
  speed:
    price: 0
    multiplier: 1
  armor:
    prot:
      price: 0
      multiplier: 1
    projprot:
      price: 0
      multiplier: 1
    fireprot:
      price: 0
      multiplier: 1
    thorns:
      price: 0
      multiplier: 1
    blastprot:
      price: 0
      multiplier: 1
    featherfall:
      price: 0
      multiplier: 1
  weapon:
    sharpness:
      price: 0
      multiplier: 1
    fireaspect:
      price: 0
      multiplier: 1
    knockback:
      price: 0
      multiplier: 1
    smite:
      price: 0
      multiplier: 1
    power:
      price: 0
      multiplier: 1
    punch:
      price: 0
      multiplier: 1
    flame:
      price: 0
      multiplier: 1
    infinity:
      price: 0
      multiplier: 1
kits:
  starter:
    items:
      '4':
        type: nether_star
        amount: 1
        name: '&b&lKit'
    armor:
      helmet: air
      chestplate: air
      leggings: air
      boots: air