Points:
  Points-On-Kill: 10
  Points-On-Death: 5
  Points-On-Respawn: 200
Options:
  Auto-Close-Upgrade-Menu: true
  Food-Heal: 1
upgrades:
  health:
    price: 0
    multiplier: 1
    multiplier2: 1
    max: 999
  speed:
    price: 0
    multiplier: 1
    multiplier2: 1
    max: 999
  armor:
    prot:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    projprot:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    fireprot:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    thorns:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    blastprot:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    featherfall:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
  weapon:
    sharpness:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    fireaspect:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    knockback:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    smite:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    power:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    punch:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    flame:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
    infinity:
      price: 0
      multiplier: 1
      multiplier2: 1
      max: 999
Abilities: 0
kits:
  starter:
    items:
      '4':
        type: nether_star
        amount: 1
        name: '&b&lKit'
    armor:
      helmet: air
      chestplate: air
      leggings: air
      boots: air
guiNextButton: ARROW
guiBackButton: BARRIER
langChatPrefix: '&6[ItemShop]'
langNotEnoughMoney: '&4&lYou do not have enough money to complete this transaction.'
langNotEnoughItems: '&4&lYou do not have enough items to complete this transaction.'
langShopOpen: '&a&lShop Opened.'
langNoPerm: '&4&lYou do not have permission to use this command.'
langReloaded: '&2&lShop reloaded!'
langGuiName: '&2&lItem Shop'
langNextPage: '&2&lNext Page'
langBackPage: '&4&lPrevious Page'
langAddedItem: '&2&lAdded item to the shop.'
langRemovedItem: '&2&lRemoved item to the shop.'
langNoHand: '&4&lThere is no item in your hand.'
langNoRem: '&4&lCould not remove item from shop.'