name: VallendiaMinigame
version: 1.0
main: me.Nikewade.VallendiaMinigame.VallendiaMinigame
commands:
  vallendia:
    aliases: [va, val, vall]
  shop:
<<<<<<< HEAD
=======
  donate:
>>>>>>> second-repo/master
depend:
  - EffectLib
  - CombatLogX
  - WorldGuard
  - WorldEdit
  - Vault
  - Parties
<<<<<<< HEAD
=======
  - Citizens
  - ProtocolLib
  - ServerTutorialPlus
>>>>>>> second-repo/master
    

